int * read_file(char file_name[50], int decimals, int * pidecimals);
int display_int_array_char(int * array, int array_size);
int display_int_array_int(int * array, int array_size);
void green();
void red();
void white();
int compare(int * calculated_pi, int * real_pi, int array_size);
int * multiply_array(int array [], int array_size, int coeff);
int * spigot_pi(int pidecimals[], int number_of_digits);
int * adapt_for_compare(int calculated_pi[],int LENGTH);
